version: "3"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
        environment:
            SA_PASSWORD: "P@ssword123"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"
        volumes:
            - sql_data_volume:/var/opt/mssql
volumes: 
    sql_data_volume: