version: '3'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    # Expose the default Sql Server port on localhost
    ports:
    - "1434:1433"
    container_name: sqlserver

    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ssword123'
      MSSQL_PID: 'Enterprise'
