services:

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest

    # Expose the default Sql Server port on localhost
    ports:
    - "1434:1433"
    container_name: sqlserver

    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'P@ssword123'
