name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Run Sql Server Image
      run: docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=$SQL_PASSWORD" -p 1433:1433 --name sql-env -d mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Sleep
      run: sleep 10s
    - name: Benchmark
      run: |
       dotnet run --project ./AppendBenchmark/AppendBenchmark.csproj --configuration Release
       dotnet run --project ./ReplaceBenchmark/ReplaceBenchmark.csproj --configuration Release
       dotnet run --project ./TupleBenchmark/TupleBenchmark.csproj --configuration Release
       dotnet run --project ./SQLConnectionBenchmark/SQLConnectionBenchmark.csproj --configuration Release
       dotnet run --project ./LinqBenchmark/LinqBenchmark.csproj --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity quiet
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  SQL_PASSWORD: P@ssword123
  SQL_CONNECTION: 'Server=.,1433;Database=master;User Id=sa;Password=$SQL_PASSWORD;'
