name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}        
    - name: Run Sql Server Image
      run: docker-compose -f "sql-server.yaml" -d up
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Sleep
      run: sleep 10s
    - name: Benchmark
      run: |
       dotnet run --project ./AppendBenchmark/AppendBenchmark.csproj --configuration Release
       dotnet run --project ./ReplaceBenchmark/ReplaceBenchmark.csproj --configuration Release
       dotnet run --project ./TupleBenchmark/TupleBenchmark.csproj --configuration Release
       dotnet run --project ./SQLConnectionBenchmark/SQLConnectionBenchmark.csproj --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SQL_CONNECTION: 'Server=.,1433;Database=master;User Id=sa;Password=P@ssword123;'
