name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}        
    - name: Run Sql Server Image
      run: docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=P@ssw0rd' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Benchmark
      run: |
       dotnet run --project ./AppendBenchmark/AppendBenchmark.csproj --configuration Release
       dotnet run --project ./ReplaceBenchmark/ReplaceBenchmark.csproj --configuration Release
       dotnet run --project ./TupleBenchmark/TupleBenchmark.csproj --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1